export enum NotificationType {
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_UNASSIGNED = 'TASK_UNASSIGNED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  TASK_UPDATED = 'TASK_UPDATED',
  COMMENT_ADDED = 'COMMENT_ADDED',
  INVITATION_RECEIVED = 'INVITATION_RECEIVED',
  INVITATION_ACCEPTED = 'INVITATION_ACCEPTED',
  INVITATION_REJECTED = 'INVITATION_REJECTED',
  INVITATION_CANCELLED = 'INVITATION_CANCELLED',
  REMOVED_FROM_PROJECT = 'REMOVED_FROM_PROJECT',
  PERMISSIONS_UPDATED = 'PERMISSIONS_UPDATED',
  TASK_DUE_SOON = 'TASK_DUE_SOON',
}
