import { MigrationInterface, QueryRunner } from "typeorm";

export class Databaseoverhaul1787366895520 implements MigrationInterface {
    name = 'Databaseoverhaul1787366895520'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "skills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "user_id" uuid, CONSTRAINT "PK_0d3212120f4ecedf90864d7e298" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "device_name" character varying, "ip_address" character varying, "expires_at" TIMESTAMP NOT NULL, "last_used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens"  ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "project_roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "level" integer NOT NULL, "permissions" jsonb NOT NULL, "is_system_role" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "project_id" uuid, CONSTRAINT "UQ_34123fed9313441d19634814f2f" UNIQUE ("project_id", "level"), CONSTRAINT "UQ_02c9b16c47f8357200ef9524434" UNIQUE ("project_id", "name"), CONSTRAINT "PK_8ac6a6996b6eaeae7b8fbb669f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_members" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_visited_at" TIMESTAMP WITH TIME ZONE, "joined_at" TIMESTAMP NOT NULL DEFAULT now(), "project_id" uuid, "user_id" uuid, "role_id" uuid NOT NULL, CONSTRAINT "UQ_b3f491d3a3f986106d281d8eb4b" UNIQUE ("project_id", "user_id"), CONSTRAINT "PK_0b2f46f804be4aea9234c78bcc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workshop_objects_type_enum" AS ENUM('TASK', 'NOTE', 'SHAPE', 'TEXT', 'SECTION_FRAME', 'TASK_CARD', 'STICKY_NOTE')`);
        await queryRunner.query(`CREATE TABLE "workshop_objects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workshop_id" uuid NOT NULL, "type" "public"."workshop_objects_type_enum" NOT NULL, "x" double precision NOT NULL, "y" double precision NOT NULL, "width" double precision NOT NULL DEFAULT '200', "height" double precision NOT NULL DEFAULT '120', "rotation" double precision NOT NULL DEFAULT '0', "z_index" integer NOT NULL DEFAULT '0', "data" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c704a14af669c3396ba7b4661aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."workshop_connections_type_enum" AS ENUM('ARROW', 'LINE', 'DASHED')`);
        await queryRunner.query(`CREATE TABLE "workshop_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workshop_id" uuid NOT NULL, "source_object_id" uuid NOT NULL, "target_object_id" uuid NOT NULL, "type" "public"."workshop_connections_type_enum" NOT NULL DEFAULT 'ARROW', "data" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cb92e80ffff83f73bc19266d662" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workshops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "draft_id" uuid NOT NULL, "viewport_x" double precision NOT NULL DEFAULT '24', "viewport_y" double precision NOT NULL DEFAULT '24', "viewport_zoom" double precision NOT NULL DEFAULT '0.82', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_2488c0cfa108a5ef0f2ee20c22" UNIQUE ("draft_id"), CONSTRAINT "PK_6d0e82a124f5b53df91c8989848" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."onboarding_drafts_status_enum" AS ENUM('DRAFT', 'SUBMITTED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "onboarding_drafts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."onboarding_drafts_status_enum" NOT NULL DEFAULT 'DRAFT', "user_id" uuid NOT NULL, "project_info" jsonb NOT NULL, "submitted_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8e59a03cf261a7807fc9a0c1cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."projects_status_enum" AS ENUM('ACTIVE', 'COMPLETED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "draft_id" uuid, "name" character varying NOT NULL, "description" text, "deadline" date, "status" "public"."projects_status_enum" NOT NULL DEFAULT 'ACTIVE', "color" character varying NOT NULL DEFAULT '#d97706', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "admin_id" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invites_status_enum" AS ENUM('ACCEPTED', 'PENDING', 'REJECTED', 'CANCELLED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "tokenHash" character varying NOT NULL, "status" "public"."invites_status_enum" NOT NULL DEFAULT 'PENDING', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "project_id" uuid, "invited_by" uuid, "role_id" uuid NOT NULL, CONSTRAINT "UQ_521aa0cf9f7e7ded862840ffa5a" UNIQUE ("tokenHash"), CONSTRAINT "PK_aa52e96b44a714372f4dd31a0af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."plans_tier_enum" AS ENUM('FREE', 'PRO', 'BUSINESS')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tier" "public"."plans_tier_enum" NOT NULL, "name" character varying NOT NULL, "description" text, "price_monthly_cents" integer NOT NULL DEFAULT '0', "price_annual_cents" integer NOT NULL DEFAULT '0', "stripe_monthly_price_id" character varying, "stripe_annual_price_id" character varying, "features" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_8f72a20c98ab97e783c5e87ea2a" UNIQUE ("tier"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'INCOMPLETE')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_billing_interval_enum" AS ENUM('MONTHLY', 'ANNUAL')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "billing_interval" "public"."subscriptions_billing_interval_enum", "stripe_customer_id" character varying, "stripe_subscription_id" character varying, "current_period_start" TIMESTAMP WITH TIME ZONE, "current_period_end" TIMESTAMP WITH TIME ZONE, "trial_start" TIMESTAMP WITH TIME ZONE, "trial_end" TIMESTAMP WITH TIME ZONE, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "ai_onboarding_generations_used" integer NOT NULL DEFAULT '0', "ai_chat_messages_used" integer NOT NULL DEFAULT '0', "ai_task_actions_used" integer NOT NULL DEFAULT '0', "ai_total_requests_used" integer NOT NULL DEFAULT '0', "ai_usage_reset_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_d0a95ef8a28188364c546eb65c1" UNIQUE ("user_id"), CONSTRAINT "REL_d0a95ef8a28188364c546eb65c" UNIQUE ("user_id"), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7aa77f6636d26cac1b731cac3a" ON "subscriptions"  ("stripe_customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a2d09d943f39912a01831a927" ON "subscriptions"  ("stripe_subscription_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "title" character varying, "bio" text, "avatar_url" character varying, "password_hash" character varying, "google_id" character varying, "reset_password_token_hash" character varying, "reset_password_expires" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_0bd5012aeb82628e07f6a1be53b" UNIQUE ("google_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "activity_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "message" character varying NOT NULL, "project_name" character varying, "entity_type" character varying, "entity_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actor_id" uuid NOT NULL, "project_id" uuid, CONSTRAINT "PK_f25287b6140c5ba18d38776a796" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0adcd018824a041e0f0becab44" ON "activity_logs"  ("project_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_generation_jobs_status_enum" AS ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "ai_generation_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requested_by" uuid NOT NULL, "prompt" text NOT NULL, "status" "public"."ai_generation_jobs_status_enum" NOT NULL DEFAULT 'PENDING', "provider" character varying NOT NULL, "model" character varying NOT NULL, "input_snapshot" jsonb NOT NULL, "output_snapshot" jsonb, "error_message" text, "project_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_280287c3e32c8d933c285eecce7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ai_chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "draft_id" uuid, "project_id" uuid, "role" character varying NOT NULL, "content" text NOT NULL, "generation_job_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_68e330d1b2a3c5368bf6d2f67cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "knowledge_chunks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "source_type" character varying(50) NOT NULL DEFAULT 'policy', "embedding" jsonb NOT NULL, "created_by" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_81af684d79d321813c41019a5cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP NOT NULL, "used_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91185d86d5d7557b19abbb2868" ON "password_reset_tokens"  ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "subtasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "is_completed" boolean NOT NULL DEFAULT false, "sort_order" double precision NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "task_id" uuid, CONSTRAINT "PK_035c1c153f0239ecc95be448d96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b52433cc346d8e1d8c6d73727" ON "subtasks"  ("task_id", "sort_order", "created_at") `);
        await queryRunner.query(`CREATE TABLE "task_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "body" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "task_id" uuid, "user_id" uuid, CONSTRAINT "PK_83b99b0b03db29d4cafcb579b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_608fdc50eb832e128ac4167078" ON "task_comments"  ("task_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "time_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "duration_min" integer NOT NULL, "logged_date" date NOT NULL, "note" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "task_id" uuid, "user_id" uuid, CONSTRAINT "PK_8657e6aaa7035da9fc7309f385a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_326f93050e88adf9873aab618c" ON "time_logs"  ("task_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."tasks_type_enum" AS ENUM('FEATURE', 'BUG', 'IMPROVEMENT', 'DOCUMENTATION', 'RESEARCH', 'CHORE')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_status_enum" AS ENUM('BACKLOG', 'TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_priority_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT')`);
        await queryRunner.query(`CREATE TYPE "public"."tasks_source_enum" AS ENUM('MANUAL', 'AI')`);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "label" character varying, "deadline" date, "type" "public"."tasks_type_enum" NOT NULL DEFAULT 'IMPROVEMENT', "status" "public"."tasks_status_enum" NOT NULL DEFAULT 'TODO', "priority" "public"."tasks_priority_enum" NOT NULL DEFAULT 'MEDIUM', "column_order" double precision NOT NULL, "source" "public"."tasks_source_enum" NOT NULL DEFAULT 'MANUAL', "attachments" jsonb NOT NULL DEFAULT '[]', "metadata" jsonb, "generation_job_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "project_id" uuid, "created_by" uuid, "assignee_id" uuid, "assigned_by_id" uuid, "board_column_id" uuid NOT NULL, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8d82387ba026be63046895fe37" ON "tasks"  ("project_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_39d8e89d36488a8e76315792f0" ON "tasks"  ("board_column_id", "column_order") `);
        await queryRunner.query(`CREATE INDEX "IDX_445d2f35e526d4d64f1be24eec" ON "tasks"  ("project_id", "column_order") `);
        await queryRunner.query(`CREATE TABLE "board_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "sort_order" double precision NOT NULL, "is_protected" boolean NOT NULL DEFAULT false, "color" character varying(20) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "project_id" uuid, CONSTRAINT "PK_e3da51ad65560ca495d3a621d32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a5ea01d2307b59a82b8263a9cf" ON "board_columns"  ("project_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_933976b397251806fa5114eed9" ON "board_columns"  ("project_id", "sort_order") `);
        await queryRunner.query(`CREATE TABLE "mini_workshops" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "project_id" uuid NOT NULL, "owner_id" uuid NOT NULL, "schema_version" smallint NOT NULL DEFAULT '2', "revision" integer NOT NULL DEFAULT '0', "scene" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_2fa0c51729679703a4cdadffab9" UNIQUE ("project_id", "owner_id"), CONSTRAINT "PK_47b27752bb2b7c05bddd06b72cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_message_reactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "emoji" character varying(32) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "message_id" uuid, "user_id" uuid, CONSTRAINT "UQ_28f6f6459cba6c27e262bf07e21" UNIQUE ("message_id", "user_id", "emoji"), CONSTRAINT "PK_61ee2549c725d0a741fa2943873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f52b492cfc5facc14fc3f1b8a2" ON "chat_message_reactions"  ("message_id") `);
        await queryRunner.query(`CREATE TYPE "public"."chat_messages_type_enum" AS ENUM('STANDARD', 'ANNOUNCEMENT', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "content" text NOT NULL, "type" "public"."chat_messages_type_enum" NOT NULL DEFAULT 'STANDARD', "is_pinned" boolean NOT NULL DEFAULT false, "pinned_at" TIMESTAMP WITH TIME ZONE, "is_edited" boolean NOT NULL DEFAULT false, "edited_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "project_id" uuid, "sender_id" uuid, "pinned_by" uuid, "parent_message_id" uuid, CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cf5a32310137fa5982060f6766" ON "chat_messages"  ("project_id", "is_pinned") `);
        await queryRunner.query(`CREATE INDEX "IDX_59eecb037cedd2b04545e72ba1" ON "chat_messages"  ("project_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "chat_message_attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "file_name" character varying(255) NOT NULL, "file_url" text NOT NULL, "file_type" character varying(100) NOT NULL, "file_size" integer NOT NULL, "storage_path" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "message_id" uuid, CONSTRAINT "PK_32257163343877aa40d676a71cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ba00841386439fa3dd8a77df9" ON "chat_message_attachments"  ("message_id") `);
        await queryRunner.query(`CREATE TABLE "chat_read_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "last_read_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "project_id" uuid, "user_id" uuid, "last_read_message_id" uuid, CONSTRAINT "UQ_0af20dc06e1af53d6378fe1a593" UNIQUE ("project_id", "user_id"), CONSTRAINT "PK_fe36275a193940908f09ef31280" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_COMPLETED', 'TASK_UPDATED', 'COMMENT_ADDED', 'INVITATION_RECEIVED', 'INVITATION_ACCEPTED', 'INVITATION_REJECTED', 'INVITATION_CANCELLED', 'REMOVED_FROM_PROJECT', 'PERMISSIONS_UPDATED', 'TASK_DUE_SOON')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "recipient_id" uuid NOT NULL, "actor_id" uuid, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying NOT NULL, "message" text NOT NULL, "project_id" uuid, "resource_type" character varying, "resource_id" character varying, "invite_token" character varying, "deduplication_key" character varying, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_314e3ac27794fc46bccaca52722" UNIQUE ("deduplication_key"), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('SUCCEEDED', 'FAILED', 'REFUNDED', 'PENDING')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "subscription_id" uuid, "stripe_payment_intent_id" character varying, "stripe_invoice_id" character varying, "amount_cents" integer NOT NULL, "currency" character varying NOT NULL DEFAULT 'usd', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "invoice_url" character varying, "receipt_url" character varying, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94c6e6376625bc6710d7dbb4b6" ON "payments"  ("stripe_payment_intent_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_070438d347258d727f7d1d3151" ON "payments"  ("stripe_invoice_id") `);
        await queryRunner.query(`CREATE TABLE "task_dependencies" ("task_id" uuid NOT NULL, "dependency_id" uuid NOT NULL, CONSTRAINT "PK_73f03e2027c01a2cb62d91728d9" PRIMARY KEY ("task_id", "dependency_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1ae6688b1bd90fffe857f4cb70" ON "task_dependencies"  ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6a76113bf7a1956147f19bf75" ON "task_dependencies"  ("dependency_id") `);
        await queryRunner.query(`ALTER TABLE "skills" ADD CONSTRAINT "FK_b6037133328ed50f9b66cd547de" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_roles" ADD CONSTRAINT "FK_acdc465c26e9c6e166b0249131b" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_b5729113570c20c7e214cf3f58d" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_members" ADD CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948" FOREIGN KEY ("role_id") REFERENCES "project_roles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workshop_objects" ADD CONSTRAINT "FK_7d2485cc6f7be8d2e20d2e33364" FOREIGN KEY ("workshop_id") REFERENCES "workshops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" ADD CONSTRAINT "FK_a1a8c8391b639c036b242bf23b4" FOREIGN KEY ("workshop_id") REFERENCES "workshops"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" ADD CONSTRAINT "FK_4fba462e2a4d87969e2eaa75da5" FOREIGN KEY ("source_object_id") REFERENCES "workshop_objects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" ADD CONSTRAINT "FK_76ef4a037e8d34d0ffbf05beacc" FOREIGN KEY ("target_object_id") REFERENCES "workshop_objects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workshops" ADD CONSTRAINT "FK_2488c0cfa108a5ef0f2ee20c225" FOREIGN KEY ("draft_id") REFERENCES "onboarding_drafts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "onboarding_drafts" ADD CONSTRAINT "FK_d5f11ff13aabc363815b435920a" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_cbf4bdc3766888f014e36835d6a" FOREIGN KEY ("draft_id") REFERENCES "onboarding_drafts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_d850927ddf251178492cf76fa38" FOREIGN KEY ("admin_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_9a75a544ecb579c8203efab71d9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_6e727f063d839c0090364ea95f3" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invites" ADD CONSTRAINT "FK_8b432fcafe8246529b0476feb59" FOREIGN KEY ("role_id") REFERENCES "project_roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_d4a993f3a163eca3d27ffee1361" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "activity_logs" ADD CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" ADD CONSTRAINT "FK_7dc2c1d74a3e65dc73244d2e341" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" ADD CONSTRAINT "FK_50668995122ab10b12e32268d36" FOREIGN KEY ("draft_id") REFERENCES "onboarding_drafts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" ADD CONSTRAINT "FK_e2d10ed0c2a083630cb0c259536" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" ADD CONSTRAINT "FK_98e1811959e59205c0e33bafd47" FOREIGN KEY ("generation_job_id") REFERENCES "ai_generation_jobs"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "FK_4cc18a71b8697e7ff1bc137f7f3" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" ADD CONSTRAINT "FK_adf12da647fbdf906de192b439b" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subtasks" ADD CONSTRAINT "FK_4f5962cd050efba5fcc6a5d86d6" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba9e465cfc707006e60aae59946" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_07ff0d4347a198527663bda63d9" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_logs" ADD CONSTRAINT "FK_5863acae12451e29b1414a3795c" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_logs" ADD CONSTRAINT "FK_b5e06aedfbf8f061e3e68ad154e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_3e08a7ca125a175cf899b09f71a" FOREIGN KEY ("assigned_by_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e1273606f4055f3229645e3faf6" FOREIGN KEY ("board_column_id") REFERENCES "board_columns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "board_columns" ADD CONSTRAINT "FK_7c488c7bbd2da68f4043dc9145e" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mini_workshops" ADD CONSTRAINT "FK_7735e58fda9b8c30ac552d800b2" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mini_workshops" ADD CONSTRAINT "FK_aa94864a234be3039a2a4e5fe2f" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message_reactions" ADD CONSTRAINT "FK_f52b492cfc5facc14fc3f1b8a2b" FOREIGN KEY ("message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message_reactions" ADD CONSTRAINT "FK_ffb1de87f23b4063db4c5ea6aa0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_39fa6812ee5a01e761f70c21196" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_ee0790677d6cf6b10fee0bebac0" FOREIGN KEY ("pinned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_1793c0449de6fa808810df6dd70" FOREIGN KEY ("parent_message_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_message_attachments" ADD CONSTRAINT "FK_7ba00841386439fa3dd8a77df98" FOREIGN KEY ("message_id") REFERENCES "chat_messages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" ADD CONSTRAINT "FK_165590d972764be0b74f360f5a9" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" ADD CONSTRAINT "FK_be9b9c1b279d63267465aedd049" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" ADD CONSTRAINT "FK_ad7b8a4ff6fc513002f73047570" FOREIGN KEY ("last_read_message_id") REFERENCES "chat_messages"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_75848dfef07fd19027e08ca81d2" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" ADD CONSTRAINT "FK_c6a76113bf7a1956147f19bf753" FOREIGN KEY ("dependency_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_c6a76113bf7a1956147f19bf753"`);
        await queryRunner.query(`ALTER TABLE "task_dependencies" DROP CONSTRAINT "FK_1ae6688b1bd90fffe857f4cb707"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_75848dfef07fd19027e08ca81d2"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" DROP CONSTRAINT "FK_ad7b8a4ff6fc513002f73047570"`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" DROP CONSTRAINT "FK_be9b9c1b279d63267465aedd049"`);
        await queryRunner.query(`ALTER TABLE "chat_read_states" DROP CONSTRAINT "FK_165590d972764be0b74f360f5a9"`);
        await queryRunner.query(`ALTER TABLE "chat_message_attachments" DROP CONSTRAINT "FK_7ba00841386439fa3dd8a77df98"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_1793c0449de6fa808810df6dd70"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_ee0790677d6cf6b10fee0bebac0"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_39fa6812ee5a01e761f70c21196"`);
        await queryRunner.query(`ALTER TABLE "chat_message_reactions" DROP CONSTRAINT "FK_ffb1de87f23b4063db4c5ea6aa0"`);
        await queryRunner.query(`ALTER TABLE "chat_message_reactions" DROP CONSTRAINT "FK_f52b492cfc5facc14fc3f1b8a2b"`);
        await queryRunner.query(`ALTER TABLE "mini_workshops" DROP CONSTRAINT "FK_aa94864a234be3039a2a4e5fe2f"`);
        await queryRunner.query(`ALTER TABLE "mini_workshops" DROP CONSTRAINT "FK_7735e58fda9b8c30ac552d800b2"`);
        await queryRunner.query(`ALTER TABLE "board_columns" DROP CONSTRAINT "FK_7c488c7bbd2da68f4043dc9145e"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e1273606f4055f3229645e3faf6"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_3e08a7ca125a175cf899b09f71a"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9fc727aef9e222ebd09dc8dac08"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "time_logs" DROP CONSTRAINT "FK_b5e06aedfbf8f061e3e68ad154e"`);
        await queryRunner.query(`ALTER TABLE "time_logs" DROP CONSTRAINT "FK_5863acae12451e29b1414a3795c"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_07ff0d4347a198527663bda63d9"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba9e465cfc707006e60aae59946"`);
        await queryRunner.query(`ALTER TABLE "subtasks" DROP CONSTRAINT "FK_4f5962cd050efba5fcc6a5d86d6"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" DROP CONSTRAINT "FK_adf12da647fbdf906de192b439b"`);
        await queryRunner.query(`ALTER TABLE "knowledge_chunks" DROP CONSTRAINT "FK_4cc18a71b8697e7ff1bc137f7f3"`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" DROP CONSTRAINT "FK_98e1811959e59205c0e33bafd47"`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" DROP CONSTRAINT "FK_e2d10ed0c2a083630cb0c259536"`);
        await queryRunner.query(`ALTER TABLE "ai_chat_messages" DROP CONSTRAINT "FK_50668995122ab10b12e32268d36"`);
        await queryRunner.query(`ALTER TABLE "ai_generation_jobs" DROP CONSTRAINT "FK_7dc2c1d74a3e65dc73244d2e341"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_3baa1aae6f896f72eafbdd057e9"`);
        await queryRunner.query(`ALTER TABLE "activity_logs" DROP CONSTRAINT "FK_d4a993f3a163eca3d27ffee1361"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_8b432fcafe8246529b0476feb59"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_6e727f063d839c0090364ea95f3"`);
        await queryRunner.query(`ALTER TABLE "invites" DROP CONSTRAINT "FK_9a75a544ecb579c8203efab71d9"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_d850927ddf251178492cf76fa38"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_cbf4bdc3766888f014e36835d6a"`);
        await queryRunner.query(`ALTER TABLE "onboarding_drafts" DROP CONSTRAINT "FK_d5f11ff13aabc363815b435920a"`);
        await queryRunner.query(`ALTER TABLE "workshops" DROP CONSTRAINT "FK_2488c0cfa108a5ef0f2ee20c225"`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" DROP CONSTRAINT "FK_76ef4a037e8d34d0ffbf05beacc"`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" DROP CONSTRAINT "FK_4fba462e2a4d87969e2eaa75da5"`);
        await queryRunner.query(`ALTER TABLE "workshop_connections" DROP CONSTRAINT "FK_a1a8c8391b639c036b242bf23b4"`);
        await queryRunner.query(`ALTER TABLE "workshop_objects" DROP CONSTRAINT "FK_7d2485cc6f7be8d2e20d2e33364"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_47b9998e6fef04f3e85e1e60948"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_e89aae80e010c2faa72e6a49ce8"`);
        await queryRunner.query(`ALTER TABLE "project_members" DROP CONSTRAINT "FK_b5729113570c20c7e214cf3f58d"`);
        await queryRunner.query(`ALTER TABLE "project_roles" DROP CONSTRAINT "FK_acdc465c26e9c6e166b0249131b"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "skills" DROP CONSTRAINT "FK_b6037133328ed50f9b66cd547de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6a76113bf7a1956147f19bf75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ae6688b1bd90fffe857f4cb70"`);
        await queryRunner.query(`DROP TABLE "task_dependencies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_070438d347258d727f7d1d3151"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94c6e6376625bc6710d7dbb4b6"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TABLE "chat_read_states"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ba00841386439fa3dd8a77df9"`);
        await queryRunner.query(`DROP TABLE "chat_message_attachments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_59eecb037cedd2b04545e72ba1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cf5a32310137fa5982060f6766"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TYPE "public"."chat_messages_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52b492cfc5facc14fc3f1b8a2"`);
        await queryRunner.query(`DROP TABLE "chat_message_reactions"`);
        await queryRunner.query(`DROP TABLE "mini_workshops"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_933976b397251806fa5114eed9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5ea01d2307b59a82b8263a9cf"`);
        await queryRunner.query(`DROP TABLE "board_columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_445d2f35e526d4d64f1be24eec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_39d8e89d36488a8e76315792f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8d82387ba026be63046895fe37"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_priority_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."tasks_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_326f93050e88adf9873aab618c"`);
        await queryRunner.query(`DROP TABLE "time_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_608fdc50eb832e128ac4167078"`);
        await queryRunner.query(`DROP TABLE "task_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b52433cc346d8e1d8c6d73727"`);
        await queryRunner.query(`DROP TABLE "subtasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91185d86d5d7557b19abbb2868"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "knowledge_chunks"`);
        await queryRunner.query(`DROP TABLE "ai_chat_messages"`);
        await queryRunner.query(`DROP TABLE "ai_generation_jobs"`);
        await queryRunner.query(`DROP TYPE "public"."ai_generation_jobs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0adcd018824a041e0f0becab44"`);
        await queryRunner.query(`DROP TABLE "activity_logs"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a2d09d943f39912a01831a927"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7aa77f6636d26cac1b731cac3a"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_billing_interval_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_tier_enum"`);
        await queryRunner.query(`DROP TABLE "invites"`);
        await queryRunner.query(`DROP TYPE "public"."invites_status_enum"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_status_enum"`);
        await queryRunner.query(`DROP TABLE "onboarding_drafts"`);
        await queryRunner.query(`DROP TYPE "public"."onboarding_drafts_status_enum"`);
        await queryRunner.query(`DROP TABLE "workshops"`);
        await queryRunner.query(`DROP TABLE "workshop_connections"`);
        await queryRunner.query(`DROP TYPE "public"."workshop_connections_type_enum"`);
        await queryRunner.query(`DROP TABLE "workshop_objects"`);
        await queryRunner.query(`DROP TYPE "public"."workshop_objects_type_enum"`);
        await queryRunner.query(`DROP TABLE "project_members"`);
        await queryRunner.query(`DROP TABLE "project_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "skills"`);
    }

}
