export enum MiniObjectType {
  SHAPE = 'SHAPE',
  TEXT = 'TEXT',
  STICKY_NOTE = 'STICKY_NOTE',
  IMAGE = 'IMAGE',
  FRAME = 'FRAME',
  FREEHAND = 'FREEHAND',
  PERSONAL_TASK = 'PERSONAL_TASK',
  BOARD_TASK_REFERENCE = 'BOARD_TASK_REFERENCE',
}
